// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXShh-XGPfxqxb_-RDrtwAmV2gRQVQuas',
    appId: '1:155640743814:web:771bf66f5a68db5d8e4e07',
    messagingSenderId: '155640743814',
    projectId: 'project-2ec94',
    authDomain: 'project-2ec94.firebaseapp.com',
    storageBucket: 'project-2ec94.firebasestorage.app',
    measurementId: 'G-WQ8DXXQ01B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5uVrl-rB7ltIbmi2_BHTaHK5lo5d6XDk',
    appId: '1:155640743814:android:8a7e3451ccd571938e4e07',
    messagingSenderId: '155640743814',
    projectId: 'project-2ec94',
    storageBucket: 'project-2ec94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmDhojaHrDvfhN_ho0ruTauWHQFj2k0dw',
    appId: '1:155640743814:ios:4c7378ccb96d30eb8e4e07',
    messagingSenderId: '155640743814',
    projectId: 'project-2ec94',
    storageBucket: 'project-2ec94.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmDhojaHrDvfhN_ho0ruTauWHQFj2k0dw',
    appId: '1:155640743814:ios:4c7378ccb96d30eb8e4e07',
    messagingSenderId: '155640743814',
    projectId: 'project-2ec94',
    storageBucket: 'project-2ec94.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXShh-XGPfxqxb_-RDrtwAmV2gRQVQuas',
    appId: '1:155640743814:web:14eedd33eae76f8b8e4e07',
    messagingSenderId: '155640743814',
    projectId: 'project-2ec94',
    authDomain: 'project-2ec94.firebaseapp.com',
    storageBucket: 'project-2ec94.firebasestorage.app',
    measurementId: 'G-LJTMGCE3VM',
  );
}
